#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using RecipiesModelNS;


namespace RecipiesModelNS	
{
	public partial class Employee
	{
		private int _employeeID;
		public virtual int EmployeeID 
		{ 
		    get
		    {
		        return this._employeeID;
		    }
		    set
		    {
		        this._employeeID = value;
		    }
		}
		
		private string _lastName;
		public virtual string LastName 
		{ 
		    get
		    {
		        return this._lastName;
		    }
		    set
		    {
		        this._lastName = value;
		    }
		}
		
		private string _firstName;
		public virtual string FirstName 
		{ 
		    get
		    {
		        return this._firstName;
		    }
		    set
		    {
		        this._firstName = value;
		    }
		}
		
		private DateTime? _birthDate;
		public virtual DateTime? BirthDate 
		{ 
		    get
		    {
		        return this._birthDate;
		    }
		    set
		    {
		        this._birthDate = value;
		    }
		}
		
		private DateTime? _hireDate;
		public virtual DateTime? HireDate 
		{ 
		    get
		    {
		        return this._hireDate;
		    }
		    set
		    {
		        this._hireDate = value;
		    }
		}
		
		private string _address;
		public virtual string Address 
		{ 
		    get
		    {
		        return this._address;
		    }
		    set
		    {
		        this._address = value;
		    }
		}
		
		private string _city;
		public virtual string City 
		{ 
		    get
		    {
		        return this._city;
		    }
		    set
		    {
		        this._city = value;
		    }
		}
		
		private string _region;
		public virtual string Region 
		{ 
		    get
		    {
		        return this._region;
		    }
		    set
		    {
		        this._region = value;
		    }
		}
		
		private string _postalCode;
		public virtual string PostalCode 
		{ 
		    get
		    {
		        return this._postalCode;
		    }
		    set
		    {
		        this._postalCode = value;
		    }
		}
		
		private string _country;
		public virtual string Country 
		{ 
		    get
		    {
		        return this._country;
		    }
		    set
		    {
		        this._country = value;
		    }
		}
		
		private string _homePhone;
		public virtual string HomePhone 
		{ 
		    get
		    {
		        return this._homePhone;
		    }
		    set
		    {
		        this._homePhone = value;
		    }
		}
		
		private string _previousExperience;
		public virtual string PreviousExperience 
		{ 
		    get
		    {
		        return this._previousExperience;
		    }
		    set
		    {
		        this._previousExperience = value;
		    }
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate 
		{ 
		    get
		    {
		        return this._modifiedDate;
		    }
		    set
		    {
		        this._modifiedDate = value;
		    }
		}
		
		private string _modifiedByUser;
		public virtual string ModifiedByUser 
		{ 
		    get
		    {
		        return this._modifiedByUser;
		    }
		    set
		    {
		        this._modifiedByUser = value;
		    }
		}
		
		private IList<SalesOrderHeader> _salesOrderHeaders = new List<SalesOrderHeader>();
		public virtual IList<SalesOrderHeader> SalesOrderHeaders 
		{ 
		    get
		    {
		        return this._salesOrderHeaders;
		    }
		}
		
		private IList<PurchaseOrderHeader> _purchaseOrderHeaders = new List<PurchaseOrderHeader>();
		public virtual IList<PurchaseOrderHeader> PurchaseOrderHeaders 
		{ 
		    get
		    {
		        return this._purchaseOrderHeaders;
		    }
		}
		
		private IList<EmployeeDepartment> _employeeDepartments = new List<EmployeeDepartment>();
		public virtual IList<EmployeeDepartment> EmployeeDepartments 
		{ 
		    get
		    {
		        return this._employeeDepartments;
		    }
		}
		
	}
}
