#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using RecipiesModelNS;


namespace RecipiesModelNS	
{
	public partial class EmployeeDepartment
	{
		private int _employeeDepartmentId;
		public virtual int EmployeeDepartmentId 
		{ 
		    get
		    {
		        return this._employeeDepartmentId;
		    }
		    set
		    {
		        this._employeeDepartmentId = value;
		    }
		}
		
		private int? _employeeId;
		public virtual int? EmployeeId 
		{ 
		    get
		    {
		        return this._employeeId;
		    }
		    set
		    {
		        this._employeeId = value;
		    }
		}
		
		private int? _departmentId;
		public virtual int? DepartmentId 
		{ 
		    get
		    {
		        return this._departmentId;
		    }
		    set
		    {
		        this._departmentId = value;
		    }
		}
		
		private int? _shiftId;
		public virtual int? ShiftId 
		{ 
		    get
		    {
		        return this._shiftId;
		    }
		    set
		    {
		        this._shiftId = value;
		    }
		}
		
		private DateTime? _startDate;
		public virtual DateTime? StartDate 
		{ 
		    get
		    {
		        return this._startDate;
		    }
		    set
		    {
		        this._startDate = value;
		    }
		}
		
		private DateTime? _endDate;
		public virtual DateTime? EndDate 
		{ 
		    get
		    {
		        return this._endDate;
		    }
		    set
		    {
		        this._endDate = value;
		    }
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate 
		{ 
		    get
		    {
		        return this._modifiedDate;
		    }
		    set
		    {
		        this._modifiedDate = value;
		    }
		}
		
		private string _modifiedByUser;
		public virtual string ModifiedByUser 
		{ 
		    get
		    {
		        return this._modifiedByUser;
		    }
		    set
		    {
		        this._modifiedByUser = value;
		    }
		}
		
		private Shift _shift;
		public virtual Shift Shift 
		{ 
		    get
		    {
		        return this._shift;
		    }
		    set
		    {
		        this._shift = value;
		    }
		}
		
		private Employee _employee;
		public virtual Employee Employee 
		{ 
		    get
		    {
		        return this._employee;
		    }
		    set
		    {
		        this._employee = value;
		    }
		}
		
		private Department _department;
		public virtual Department Department 
		{ 
		    get
		    {
		        return this._department;
		    }
		    set
		    {
		        this._department = value;
		    }
		}
		
	}
}
