//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipiesModelNS
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Inventory
    {
        public int InventoryId { get; set; }
        private Nullable<System.DateTime> ForDate { get; set; }
        public Nullable<decimal> AverageUnitPrice { get; set; }
        public Nullable<double> QuantityByDocuments { get; set; }
        public Nullable<double> ValueByDocuments { get; set; }
        public Nullable<double> StocktakeQuantity { get; set; }
        public Nullable<double> StocktakeValue { get; set; }
        public Nullable<double> DeficiencyQuantity { get; set; }
        public Nullable<double> DeficiencyValue { get; set; }
        public Nullable<double> SurplusQuantity { get; set; }
        public Nullable<double> SurplusValue { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedByUser { get; set; }
    }
}
