//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipiesModelNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVendor
    {
        public int ProductVendorId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> UnitMeasureId { get; set; }
        public Nullable<double> AverageLeadTime { get; set; }
        public Nullable<decimal> StandardPrice { get; set; }
        public Nullable<decimal> LastReceiptCost { get; set; }
        public Nullable<System.DateTime> LastReceiptDate { get; set; }
        public Nullable<double> MinOrderQuantity { get; set; }
        public Nullable<double> MaxOrderQuantity { get; set; }
        public Nullable<double> OnOrderQuantity { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedByUser { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UnitMeasure UnitMeasure { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
