//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipiesModelNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductVendors = new HashSet<ProductVendor>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.ProductInventories = new HashSet<ProductInventory>();
            this.ProductWastes = new HashSet<ProductWaste>();
            this.ProductIngredients = new HashSet<ProductIngredient>();
        }
    
        public int ProductId { get; set; }
        public Nullable<int> UnitMeasureId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<double> UnitsInStock { get; set; }
        public Nullable<double> UnitsOnOrder { get; set; }
        public Nullable<double> ReorderLevel { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedByUser { get; set; }
        public double StockValue { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Store Store { get; set; }
        public virtual UnitMeasure UnitMeasure { get; set; }
        public virtual ICollection<ProductVendor> ProductVendors { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual ICollection<ProductInventory> ProductInventories { get; set; }
        public virtual ICollection<ProductWaste> ProductWastes { get; set; }
        public virtual ICollection<ProductIngredient> ProductIngredients { get; set; }
    }
}
