//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipiesModelNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductWasteHeader
    {
        public ProductWasteHeader()
        {
            this.ProductWastes = new HashSet<ProductWaste>();
        }
    
        public int ProductWasteHeaderId { get; set; }
        public Nullable<System.DateTime> ForDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedByUser { get; set; }
    
        public virtual ICollection<ProductWaste> ProductWastes { get; set; }
    }
}
