#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using RecipiesModelNS;


namespace RecipiesModelNS	
{
	public partial class PurchaseOrderStatus
	{
		private int _purchaseOrderStatusId;
		public virtual int PurchaseOrderStatusId 
		{ 
		    get
		    {
		        return this._purchaseOrderStatusId;
		    }
		    set
		    {
		        this._purchaseOrderStatusId = value;
		    }
		}
		
		private string _name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate 
		{ 
		    get
		    {
		        return this._modifiedDate;
		    }
		    set
		    {
		        this._modifiedDate = value;
		    }
		}
		
		private string _modifiedByUser;
		public virtual string ModifiedByUser 
		{ 
		    get
		    {
		        return this._modifiedByUser;
		    }
		    set
		    {
		        this._modifiedByUser = value;
		    }
		}
		
		private bool? _isVisible;
		public virtual bool? IsVisible 
		{ 
		    get
		    {
		        return this._isVisible;
		    }
		    set
		    {
		        this._isVisible = value;
		    }
		}
		
		private IList<PurchaseOrderHeader> _purchaseOrderHeaders = new List<PurchaseOrderHeader>();
		public virtual IList<PurchaseOrderHeader> PurchaseOrderHeaders 
		{ 
		    get
		    {
		        return this._purchaseOrderHeaders;
		    }
		}
		
	}
}
