//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipiesModelNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredient
    {
        public int RecipeIngredientId { get; set; }
        public Nullable<int> ParentRecipeId { get; set; }
        public Nullable<int> IngredientRecipeId { get; set; }
        public Nullable<double> QuantityPerPortion { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedByUser { get; set; }
        public double TotalValue { get; set; }
    
        public virtual Recipe IngredientRecipe { get; set; }
        public virtual Recipe ParentRecipe { get; set; }
    }
}
