#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using RecipiesModelNS;


namespace RecipiesModelNS	
{
	public partial class SalesOrderDetail
	{
		private int _salesOrderDetailId;
		public virtual int SalesOrderDetailId 
		{ 
		    get
		    {
		        return this._salesOrderDetailId;
		    }
		    set
		    {
		        this._salesOrderDetailId = value;
		    }
		}
		
		private int? _salesOrderHeaderId;
		public virtual int? SalesOrderHeaderId 
		{ 
		    get
		    {
		        return this._salesOrderHeaderId;
		    }
		    set
		    {
		        this._salesOrderHeaderId = value;
		    }
		}
		
		private int? _recipeId;
		public virtual int? RecipeId 
		{ 
		    get
		    {
		        return this._recipeId;
		    }
		    set
		    {
		        this._recipeId = value;
		    }
		}
		
		private double? _orderQuantity;
		public virtual double? OrderQuantity 
		{ 
		    get
		    {
		        return this._orderQuantity;
		    }
		    set
		    {
		        this._orderQuantity = value;
		    }
		}
		
		private decimal? _unitPrice;
		public virtual decimal? UnitPrice 
		{ 
		    get
		    {
		        return this._unitPrice;
		    }
		    set
		    {
		        this._unitPrice = value;
		    }
		}
		
		private double? _unitPriceDiscount;
		public virtual double? UnitPriceDiscount 
		{ 
		    get
		    {
		        return this._unitPriceDiscount;
		    }
		    set
		    {
		        this._unitPriceDiscount = value;
		    }
		}
		
		private double _lineTotal;
		public virtual double LineTotal 
		{ 
		    get
		    {
		        return this._lineTotal;
		    }
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate 
		{ 
		    get
		    {
		        return this._modifiedDate;
		    }
		    set
		    {
		        this._modifiedDate = value;
		    }
		}
		
		private string _modifiedByUser;
		public virtual string ModifiedByUser 
		{ 
		    get
		    {
		        return this._modifiedByUser;
		    }
		    set
		    {
		        this._modifiedByUser = value;
		    }
		}
		
		private Recipe _recipe;
		public virtual Recipe Recipe 
		{ 
		    get
		    {
		        return this._recipe;
		    }
		    set
		    {
		        this._recipe = value;
		    }
		}
		
		private SalesOrderHeader _salesOrderHeader;
		public virtual SalesOrderHeader SalesOrderHeader 
		{ 
		    get
		    {
		        return this._salesOrderHeader;
		    }
		    set
		    {
		        this._salesOrderHeader = value;
		    }
		}
		
	}
}
