#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using RecipiesModelNS;


namespace RecipiesModelNS	
{
	public partial class Shift
	{
		private int _shiftId;
		public virtual int ShiftId 
		{ 
		    get
		    {
		        return this._shiftId;
		    }
		    set
		    {
		        this._shiftId = value;
		    }
		}
		
		private string _name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private DateTime? _startHour;
		public virtual DateTime? StartHour 
		{ 
		    get
		    {
		        return this._startHour;
		    }
		    set
		    {
		        this._startHour = value;
		    }
		}
		
		private DateTime? _endHour;
		public virtual DateTime? EndHour 
		{ 
		    get
		    {
		        return this._endHour;
		    }
		    set
		    {
		        this._endHour = value;
		    }
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate 
		{ 
		    get
		    {
		        return this._modifiedDate;
		    }
		    set
		    {
		        this._modifiedDate = value;
		    }
		}
		
		private string _modifiedByUser;
		public virtual string ModifiedByUser 
		{ 
		    get
		    {
		        return this._modifiedByUser;
		    }
		    set
		    {
		        this._modifiedByUser = value;
		    }
		}
		
		private IList<EmployeeDepartment> _employeeDepartments = new List<EmployeeDepartment>();
		public virtual IList<EmployeeDepartment> EmployeeDepartments 
		{ 
		    get
		    {
		        return this._employeeDepartments;
		    }
		}
		
	}
}
