#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using RecipiesModelNS;


namespace RecipiesModelNS	
{
	public partial class ShipMethod
	{
		private int _shipMethodId;
		public virtual int ShipMethodId 
		{ 
		    get
		    {
		        return this._shipMethodId;
		    }
		    set
		    {
		        this._shipMethodId = value;
		    }
		}
		
		private string _name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private decimal? _shipBase;
		public virtual decimal? ShipBase 
		{ 
		    get
		    {
		        return this._shipBase;
		    }
		    set
		    {
		        this._shipBase = value;
		    }
		}
		
		private decimal? _shipRate;
		public virtual decimal? ShipRate 
		{ 
		    get
		    {
		        return this._shipRate;
		    }
		    set
		    {
		        this._shipRate = value;
		    }
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate 
		{ 
		    get
		    {
		        return this._modifiedDate;
		    }
		    set
		    {
		        this._modifiedDate = value;
		    }
		}
		
		private string _modifiedByUser;
		public virtual string ModifiedByUser 
		{ 
		    get
		    {
		        return this._modifiedByUser;
		    }
		    set
		    {
		        this._modifiedByUser = value;
		    }
		}
		
		private IList<PurchaseOrderHeader> _purchaseOrderHeaders = new List<PurchaseOrderHeader>();
		public virtual IList<PurchaseOrderHeader> PurchaseOrderHeaders 
		{ 
		    get
		    {
		        return this._purchaseOrderHeaders;
		    }
		}
		
	}
}
