#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using RecipiesModelNS;


namespace RecipiesModelNS	
{
	public partial class UnitMeasure
	{
		private int _unitMeasureId;
		public virtual int UnitMeasureId 
		{ 
		    get
		    {
		        return this._unitMeasureId;
		    }
		    set
		    {
		        this._unitMeasureId = value;
		    }
		}
		
		private string _name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private bool? _isBaseUnit;
		public virtual bool? IsBaseUnit 
		{ 
		    get
		    {
		        return this._isBaseUnit;
		    }
		    set
		    {
		        this._isBaseUnit = value;
		    }
		}
		
		private int? _baseUnitId;
		public virtual int? BaseUnitId 
		{ 
		    get
		    {
		        return this._baseUnitId;
		    }
		    set
		    {
		        this._baseUnitId = value;
		    }
		}
		
		private double? _baseUnitFactor;
		public virtual double? BaseUnitFactor 
		{ 
		    get
		    {
		        return this._baseUnitFactor;
		    }
		    set
		    {
		        this._baseUnitFactor = value;
		    }
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate 
		{ 
		    get
		    {
		        return this._modifiedDate;
		    }
		    set
		    {
		        this._modifiedDate = value;
		    }
		}
		
		private string _modifiedByUser;
		public virtual string ModifiedByUser 
		{ 
		    get
		    {
		        return this._modifiedByUser;
		    }
		    set
		    {
		        this._modifiedByUser = value;
		    }
		}
		
		private IList<ProductVendor> _productVendors = new List<ProductVendor>();
		public virtual IList<ProductVendor> ProductVendors 
		{ 
		    get
		    {
		        return this._productVendors;
		    }
		}
		
		private IList<Product> _products = new List<Product>();
		public virtual IList<Product> Products 
		{ 
		    get
		    {
		        return this._products;
		    }
		}
		
		private IList<PurchaseOrderDetail> _purchaseOrderDetails = new List<PurchaseOrderDetail>();
		public virtual IList<PurchaseOrderDetail> PurchaseOrderDetails 
		{ 
		    get
		    {
		        return this._purchaseOrderDetails;
		    }
		}
		
	}
}
